### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by ArturoAngonJose** [SistemasTecTlaxiaco/infografia-ArturoAngonJose#2]
[Infografia_Arturo Angon Jose.pdf](https://github.com/SistemasTecTlaxiaco/infografia-ArturoAngonJose/files/7148998/Infografia_Arturo.Angon.Jose.pdf)

**Comment by IsaHuerta23** [comment]
Redacción y Ortografía: 3pts.
Exposición de ideas centrales: 3pts.
Organización de la información: 3pts.
Uso de imágenes y colores: 1pto.
Presentación visual: 3pts.
Referencias: 0pts.
Presentación: 3pts.

Calificación: 16.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
